# Generated by Django 4.0.5 on 2022-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма прихода'),
        ),
        migrations.AlterField(
            model_name='item',
            name='outcome_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма расхода'),
        ),
    ]
