# Generated by Django 4.0.5 on 2022-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_item_income_amount_alter_item_outcome_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма выводов'),
        ),
        migrations.AddField(
            model_name='itemrow',
            name='is_withdraw',
            field=models.BooleanField(default=False, verbose_name='Это вывод'),
        ),
    ]
