# Generated by Django 4.0.5 on 2022-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_item_withdraw_amount_itemrow_is_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
