# Generated by Django 4.0.5 on 2022-06-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrow',
            name='item',
        ),
        migrations.CreateModel(
            name='ItemAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер счета')),
                ('income_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма прихода')),
                ('outcome_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма расхода')),
                ('withdraw_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма выводов')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='data.item', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Расчетный счет',
                'verbose_name_plural': 'Расчетные счета',
            },
        ),
        migrations.AddField(
            model_name='itemrow',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='data.itemaccount', verbose_name='Р/С'),
        ),
    ]
