# Generated by Django 4.0.5 on 2022-06-09 19:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_itemrow_item_itemaccount_itemrow_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrow',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
