# Generated by Django 4.0.5 on 2022-06-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_itemrow_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название месяца')),
            ],
            options={
                'verbose_name': 'Месяца',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.AddField(
            model_name='itemaccount',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Лимит в месяц'),
        ),
        migrations.AddField(
            model_name='itemrow',
            name='created',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='itemrow',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.month', verbose_name='Месяц'),
        ),
    ]
