# Generated by Django 4.0.5 on 2022-06-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_month_itemaccount_limit_itemrow_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowMonthAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма прихода')),
                ('outcome_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма расхода')),
                ('withdraw_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма выводов')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.itemrow')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.month')),
            ],
        ),
    ]
